//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.04.22 at 01:54:52 AM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xmlns.example.com/location/details", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.country.city.wsdl;
